version: '3.8'

services:
  jsp-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - ${USERPROFILE}/Documentos/Docker/teste/PostgreSQL/baseapp:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8089:8080